### ISSUE TITLE
Suricata+DPDK Fails in IPS or Bypass mode

### ISSUE THREAD

**Issue by edsealing** [edsealing/suricata#2]
When starting suricata with "opmode: bypass" or "opmode: bypass", suricata fails to launch. Error produced:

[ERRCODE: SC_ERR_DPDKINTEL_CONFIG_FAILED(285)] -  Ports in DPDK 2 Config-file 0

**Comment by edsealing** [comment]
IPS and Bypass mode requires mapping the interfaces in the suricata.yaml file. This can be accomplished in the following example configuration:

```
  inputs:
  - interface: 0000:03:00.0
    copy-interface: 0000:03:00.1
  - interface: 0000:03:00.1
    copy-interface: 0000:03:00.0
```

In this configuration, Port 0 (0000:03:00.0) outbound traffic is mapped to Port 1 (0000:03:00.1) with: 

```
  - interface: 0000:03:00.0
    copy-interface: 0000:03:00.1
```

Conversely, Port 1 (0000:03:00.1) inbound traffic is mapped to Port 0 (0000:03:00.0) with:

```
  - interface: 0000:03:00.1
    copy-interface: 0000:03:00.0
```

Closing Ticket as
